# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 516d15b38d16d39c2af03f0899c24c5535b9d8dcf632baa0ee8cd9420d7df22579015a546de79b9e46e84b260678ee9c67b43bb8185fe0898cf650bbb3d2eebd

test:
  secret_key_base: c2f27fa0888a62a306efff6d3a03d40b9aee0f895da70687150281379beec24a1483e6c4fc9207a4e8b6a6647e625870688c8c645a7db1acbe229ea1229d692f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
